name: Build and Release APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.sha.outputs.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create google-services.json
        run: |
          # Use heredoc to preserve JSON formatting
          cat << EOF > app/google-services.json
          ${{ secrets.GOOGLE_SERVICES_JSON }}
          EOF

      - name: Create secrets.xml
        run: |
          mkdir -p app/src/main/res/values
          cat << EOF > app/src/main/res/values/secrets.xml
          <?xml version="1.0" encoding="utf-8"?>
          <resources>
              <string name="fcm_server_key">${{ secrets.FCM_SERVER_KEY }}</string>
          </resources>
          EOF

      - name: Get short SHA
        id: sha
        run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Upload config files
        uses: actions/upload-artifact@v4
        with:
          name: config-files
          path: |
            app/google-services.json
            app/src/main/res/values/secrets.xml

  build-check:
    name: Build Checks
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download config files
        uses: actions/download-artifact@v4
        with:
          name: config-files
          # Overwrite existing files from checkout
          path: ./

      - name: Verify files exist
        run: |
          ls -la app/google-services.json
          ls -la app/src/main/res/values/secrets.xml

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: gradle

      - name: Change Gradle Wrapper Permissions
        run: chmod +x gradlew

      - name: Run build checks
        run: ./gradlew check

  build:
    name: Build APK
    runs-on: ubuntu-latest
    needs: [ setup, build-check ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download config files
        uses: actions/download-artifact@v4
        with:
          name: config-files
          path: ./

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: gradle

      - name: Change Gradle Wrapper Permissions
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 1

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 1.0-${{ needs.setup.outputs.short_sha }}
          name: "Release ${{ needs.setup.outputs.short_sha }}"
          body: |
            ## What's Changed
            **Full Changelog**: ${{ github.server_url }}/${{ github.repository }}/compare/${{ github.event.before }}...${{ github.sha }}
          files: |
            app/build/outputs/apk/debug/app-debug.apk