name: Build Apk

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: gradle

      - name: Create google-services.json
        run: printf '%s' "${{ secrets.GOOGLE_SERVICES_JSON }}" > app/google-services.json

      - name: Create secrets.xml
        run: |
          # Write content without adding trailing newline
          printf '%s' "${{ secrets.SECRETS_XML }}" > app/src/main/res/values/secrets.xml
          # Remove UTF-8 BOM if present
          sed -i '1s/^\xEF\xBB\xBF//' app/src/main/res/values/secrets.xml

      - name: Validate XML format
        run: |
          # Check if XML is well-formed
          xmllint --noout app/src/main/res/values/secrets.xml

      - name: Fix line endings
        run: |
          dos2unix app/google-services.json
          dos2unix app/src/main/res/values/secrets.xml

      - name: Change Gradle Wrapper Permissions
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # Remaining steps remain the same...